PORTNAME= influxdb3
DISTVERSIONPREFIX= v
DISTVERSION= 3.4.0
CATEGORIES= databases

MAINTAINER= yak1ex@gmail.com
COMMENT= Scalable datastore for metrics, events, and real-time analytics
WWW= https://github.com/influxdata/influxdb

USES= cargo
USE_GITHUB= yes
GH_ACCOUNT= influxdata
GH_PROJECT= influxdb

.include <bsd.port.mk>
